services:
  app:
    container_name: springboot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
#      - "7171:8000"
      - "7171:8181"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - spring-network
    deploy:
      resources:
        limits:
          cpus: '12'
          memory: 16G

networks:
  spring-network:
    driver: bridge